# Generated by Django 5.2rc1 on 2026-01-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
