# Generated by Django 5.2rc1 on 2026-01-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_loginhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='registrations/')),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('parent', 'Parent')], max_length=10)),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('experience', models.IntegerField(default=0)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LoginHistory',
        ),
    ]
