# Generated by Django 5.2rc1 on 2026-01-06 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0003_registration_delete_loginhistory'),
        ('teachers', '0002_teacherprofile_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='bookings/')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parents.parentprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacherprofile')),
            ],
        ),
    ]
