# Generated by Django 5.2rc1 on 2026-01-06 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0004_booking'),
        ('teachers', '0002_teacherprofile_is_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.AlterField(
            model_name='booking',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_bookings', to='parents.parentprofile'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_bookings', to='teachers.teacherprofile'),
        ),
    ]
