# Generated by Django 5.2rc1 on 2026-01-07 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0005_delete_registration_alter_booking_parent_and_more'),
        ('teachers', '0002_teacherprofile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parents.parentprofile'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacherprofile'),
        ),
    ]
