# Generated by Django 5.2rc1 on 2026-01-07 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parents', '0006_parentprofile_name_alter_booking_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('school', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='registrations/')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parents.parentprofile')),
            ],
        ),
    ]
